<?php

    function ajax_portfolio_menu() {
        $items['portfolio-piece/%/%'] = array(
            'access arguments' => array('access content'),
            'page callback' => 'ajax_portfolio_node_display',
            'page arguments' => array(1, 2),
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function ajax_portfolio_node_display($js, $node_id) {
        $node = node_load($node_id);
        if ($js == 'nojs') {
        drupal_goto('node/' . $node->nid);
    }

    $build = node_view($node);
    $html = render($build);

    $commands[] = ajax_command_html('#portfolio-project-ajax-view', $html);
    print ajax_render($commands);
    exit;

}
