<?php

function ajax_salon_menu() {
    $items['ajax-salon'] = array(
        'title' => 'AJAX Salon',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ajax_salon_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function ajax_salon_form($form, &$form_state) {

    $options_first = ajax_salon_type_dropdown();
    $selected = isset($form_state['values']['dropdown_first']) ? $form_state['values']['dropdown_first'] : key($options_first);

    $form['dropdown_first'] = array(
        '#type' => 'select',
        '#title' => 'Service',
        '#options' => $options_first,
        '#default_value' => $selected,
        '#ajax' => array(
            'callback' => 'ajax_salon_dropdown_callback',
            'wrapper' => 'dropdown-second-replace',
            'progress' => array('type' => 'none'),
        ),
    );

    $form['dropdown_second'] = array(
        '#type' => 'select',
        '#title' => t("Hairdresser") . " " . $options_first[$selected],
        '#prefix' => '<div id="dropdown-second-replace">',
        '#suffix' => '</div>',
        '#options' => ajax_salon_stylist_dropdown($selected),
        '#default_value' => isset($form_state['values']['dropdown_second']) ? $form_state['values']['dropdown_second'] : '',
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#ajax' => array(
          'callback' => 'ajax_salon_submit',
          'wrapper' => 'choice',
        ),
        '#value' => t('Submit'),
    );

    $form['choice'] = array(
    '#type' => 'fieldset',
    '#title' => t("Your Choice"),
    '#prefix' => "<div id='choice'>",
    '#suffix' => '</div>',
);
    return $form;
}

function ajax_salon_dropdown_callback($form, $form_state) {
    return $form['dropdown_second'];
}

function ajax_salon_type_dropdown() {
    return drupal_map_assoc(
        array(
            t('Hair Cut'),
            t('Makeup'),
        )
    );
}

function ajax_salon_stylist_dropdown($type = '') {
    $options = array(
        t('Hair Cut') => drupal_map_assoc(
            array(
                t('Megan Miller'),
                t('Sydney Sovereign'),
            )
        ),
        t('Makeup') => drupal_map_assoc(
            array(
                t('Mary Warrington'),
                t('Mark Aldrich'),
            )
        ),
    );

    if (isset($options[$type])) {
        return $options[$type];
    } else {
        return array();
    }
}

function ajax_salon_submit($form_id, &$form_state) {

    return $form_state['choice']['#description'] = t("You have chosen a @first by @second", array('@first' => $form_state['values']['dropdown_first'], '@second' => $form_state['values']['dropdown_second']));

}
