<?php

function dna_generator_menu() {
    $items['dna_generator_input'] = array(
        'title' => 'DNA Generator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_generator_output'] = array(
        'title' => 'DNA Generator',
        'page callback' => 'dna_generator_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['box'] = array(
        '#type' => 'fieldset',
        '#title' => 'Create DNA Double Helix',
    );
    $form['box']['input'] = array(
        '#type' => 'textfield',
        '#title' => t('Enter a string of nucleotides - A, T, C, G'),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_nucleotide'),
    );

    $form['box']['submit'] = array(
        '#value' => t('Submit'),
        '#type' => 'submit',
    );
    return $form;
}

//validation
function element_validate_nucleotide($element) {
    $element_array = str_split(strtoupper($element['#value']));
    foreach($element_array as $letter) {
        if ($letter !== 'A' && $letter !== 'T' && $letter !== 'C' && $letter !== 'G') {
            form_error($element, t('Please only enter nucleotides and omit any spaces.'));
        }
    }
}

//submit
function dna_form_submit($form, &$form_state) {
    $this->dna_generator($form_state['values']['input']);
    $form_state['redirect'] = 'dna_generator_output';
}


function dna_generator($input) {
    $array_one = str_split(strtoupper($input));
    $array_two = array();

    $nucleotide_array = array(
        'T' => 'A',
        'A' => 'T',
        'C' => 'G',
        'G' => 'C',
    );

    foreach($array_one as $letter) {
        foreach ($nucleotide_array as $nucleotide_one => $nucleotide_two) {
            if ($letter === $nucleotide_one) {
                array_push($array_two, $nucleotide_two);
            }
        }
    }

    $string_two = implode($array_two);
    $_SESSION['helix_one'] = $string_one;
    $_SESSION['helix_two'] = $string_two;
}

function dna_generator_results() {
    return "<p>" . $_SESSION['helix_one'] . "</p><p>" . $_SESSION['helix_two'] . "</p>";
}
