<?php

function simple_ajax_menu() {
    $items = array();

    $items['examples/ajax_example'] = array(
        'title' => 'Simple Ajax form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('simple_ajax_example'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function simple_ajax_example($form, &$form_state) {
    $form = array();
    $form['changethis'] = array(
        '#title' => t("What is the sum of 2+2?"),
        '#type' => 'select',
        '#options' => array(
            '2' => '2',
            '3' => '3',
            '4' => '4',
            '5' => '5',
        ),
        '#ajax' => array(
            'callback' => 'ajax_callback_answer',
            'wrapper' => 'replace_fieldset_div',
            'effect' => 'fade',
            'progress' => array('type' => 'none'),
        ),
    );

    $form['replace_fieldset'] = array(
        '#type' => 'fieldset',
        '#title' => t("Answer"),
        '#prefix' => "<div id='replace_fieldset_div'>",
        '#suffix' => '</div>',
    );

    if (!empty($form_state['values']['changethis'])) {
        $guess = $form_state['values']['changethis'];
        if($guess == '4') {
            $form['replace_fieldset']['#description'] = t("Your answer was correct!");
        } else {
            $form['replace_fieldset']['#description'] = t("Your answer was incorrect. Try again!");
        }
    }
    return $form;
}

function ajax_callback_answer($form, $form_state) {
    return $form['replace_fieldset'];
}
