<?php

function ajax_time_menu() {
    $items['ajax-time/%/test'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'ajax_time',
        'page arguments' => array(1),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function ajax_time($ajax) {
    $time = t('The current time is: !time', array('!time' => date('Y-m-d H:i:s')));

    if ($ajax == 'nojs') {
        return array(
            '#markup' => $time,
        );
    }

    $commands = array();

    $commands[] = ajax_command_replace('#ajax-time', "<div id='ajax-time'>" . $time . "</div>");

    print ajax_render($commands);
    print_r($ajax);
    exit;

//old code
    // if ($ajax == 'ajax') {
    //     $commands = array();
    //
    //     $commands[] = ajax_command_replace('#ajax-time', "<div id='ajax-time'>" . $time . "</div>");
    //
    //     print ajax_render($commands);
    //
    // } else {
    //     return array(
    //         '#markup' => $time,
    //     );
    // }
}
